import React, { useEffect, useState } from "react";
import API from "../api/axios.js";
import { toast } from "react-toastify";

const sponsorBlank={name:"",company:"",contact_person:"",email:"",tier:"Silver",amount:0,contract_status:"Prospect",payment_status:"Pending",deliverable_status:"Pending",performance_score:70,roi:1,event_name:""};
const incidentBlank={title:"",description:"",category:"Other",location:"",event_name:"",reported_by:"",assigned_to:"",severity:"Medium",priority:"Medium",status:"Open"};
const money=n=>`₹${Number(n||0).toLocaleString("en-IN")}`;
function Card({children,className=""}){return <div className={`card ${className}`}>{children}</div>}
function Field({label,value,onChange,type="text",children}){return <label className="block"><span className="label">{label}</span>{children||<input className="input" type={type} value={value??""} onChange={e=>onChange(e.target.value)}/>}</label>}
function Stat({label,value,accent="text-violet-600"}){return <Card><p className="text-xs font-semibold uppercase tracking-wide text-gray-400">{label}</p><p className={`mt-2 text-2xl font-bold ${accent}`}>{value}</p></Card>}

export default function Milestone3({section="monitoring"}){
 const [sponsors,setSponsors]=useState([]),[incidents,setIncidents]=useState([]),[alerts,setAlerts]=useState([]),[stats,setStats]=useState({}),[form,setForm]=useState(sponsorBlank),[incidentForm,setIncidentForm]=useState(incidentBlank),[editing,setEditing]=useState(null),[question,setQuestion]=useState(""),[answer,setAnswer]=useState("");
 const load=()=>Promise.all([API.get("/sponsors"),API.get("/incidents"),API.get("/alerts"),API.get("/sponsors/analytics"),API.get("/monitoring")]).then(([s,i,a,sa,m])=>{setSponsors(s.data.sponsors);setIncidents(i.data.incidents);setAlerts(a.data.alerts);setStats({...sa.data,...m.data})}).catch(e=>toast.error(e.message));
 useEffect(()=>{load();const t=setInterval(load,30000);return()=>clearInterval(t)},[]);
 const saveSponsor=async e=>{e.preventDefault();try{if(editing) await API.put(`/sponsors/${editing}`,form);else await API.post("/sponsors",form);toast.success(editing?"Sponsor updated":"Sponsor added");setForm(sponsorBlank);setEditing(null);load()}catch(e){toast.error(e.message)}};
 const saveIncident=async e=>{e.preventDefault();try{await API.post("/incidents",incidentForm);toast.success("Incident created");setIncidentForm(incidentBlank);load()}catch(e){toast.error(e.message)}};
 const remove=async(id,type)=>{if(!confirm("Delete this record?"))return;await API.delete(`/${type}/${id}`);load()};
 const updateIncident=async(id,status)=>{await API.put(`/incidents/${id}`,{status});toast.success(`Incident ${status.toLowerCase()}`);load()};
 const ask=async kind=>{try{const r=await API.post(`/ai/${kind}`,{question});setAnswer(r.data.answer)}catch(e){toast.error(e.message)}};
 if(section==="monitoring") return <div className="space-y-6"><header><p className="text-sm font-semibold text-violet-600">MILESTONE 3 • LIVE VIEW</p><h1 className="text-3xl font-bold text-gray-900">Real-Time Operations</h1><p className="text-gray-500 mt-1">Refreshes every 30 seconds • local AI fallback enabled</p></header><div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Stat label="Active sponsors" value={stats.active_sponsors}/><Stat label="Sponsorship revenue" value={money(stats.revenue)} accent="text-emerald-600"/><Stat label="Open incidents" value={stats.open_incidents} accent="text-orange-600"/><Stat label="Critical incidents" value={stats.critical_incidents} accent="text-red-600"/><Stat label="Active alerts" value={stats.active_alerts}/><Stat label="Pending deliverables" value={stats.pending_deliverables}/><Stat label="Pending payments" value={stats.pending_payments}/><Stat label="Avg performance" value={`${stats.average_performance||0}%`}/></div><div className="grid lg:grid-cols-2 gap-6"><Card><h2 className="font-bold text-lg mb-4">Incident priority</h2>{Object.entries(stats.incidents_by_priority||{}).map(([k,v])=><div className="mb-3" key={k}><div className="flex justify-between text-sm mb-1"><span>{k}</span><b>{v}</b></div><div className="h-2 bg-gray-100 rounded-full"><div className={`h-2 rounded-full ${k==="Critical"?"bg-red-500":k==="High"?"bg-orange-500":"bg-violet-500"}`} style={{width:`${Math.min(100,v*30)}%`}}/></div></div>)}</Card><Card><h2 className="font-bold text-lg mb-4">Operational alerts</h2>{alerts.map(a=><div key={a.id} className="flex justify-between gap-3 py-3 border-b last:border-0"><div><span className="badge bg-red-50 text-red-600">{a.severity}</span><p className="text-sm mt-1">{a.message}</p></div>{a.status!=="Resolved"&&<button className="btn-secondary text-xs px-3 py-1" onClick={()=>API.put(`/alerts/${a.id}/acknowledge`).then(load)}>Acknowledge</button>}</div>)}</Card></div></div>;
 if(section==="sponsors") return <div className="space-y-6"><header><h1 className="text-3xl font-bold">Sponsorships</h1><p className="text-gray-500">Manage contracts, benefits, payments and sponsor ROI.</p></header><div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Stat label="Total sponsors" value={stats.total}/><Stat label="Revenue" value={money(stats.revenue)} accent="text-emerald-600"/><Stat label="Avg performance" value={`${stats.average_performance||0}%`}/><Stat label="Avg ROI" value={`${stats.roi||0}x`} accent="text-amber-600"/></div><div className="grid xl:grid-cols-3 gap-6"><Card className="xl:col-span-2 overflow-auto"><table className="w-full text-sm"><thead><tr className="text-left text-gray-400 border-b"><th className="pb-3">Sponsor</th><th>Tier</th><th>Value</th><th>Performance</th><th>Status</th><th></th></tr></thead><tbody>{sponsors.map(s=><tr key={s.id} className="border-b last:border-0"><td className="py-4"><b>{s.company}</b><p className="text-xs text-gray-400">{s.name}</p></td><td><span className="badge bg-violet-50 text-violet-700">{s.tier}</span></td><td>{money(s.amount)}<p className="text-xs text-gray-400">{s.roi}x ROI</p></td><td>{s.performance_score}%</td><td>{s.contract_status}<p className={`text-xs ${s.payment_status==="Paid"?"text-emerald-600":"text-orange-600"}`}>{s.payment_status}</p></td><td className="whitespace-nowrap"><button className="text-violet-600 mr-3" onClick={()=>{setEditing(s.id);setForm(s)}}>Edit</button><button className="text-red-500" onClick={()=>remove(s.id,"sponsors")}>Delete</button></td></tr>)}</tbody></table></Card><Card><h2 className="font-bold mb-4">{editing?"Edit sponsor":"Add sponsor"}</h2><form onSubmit={saveSponsor} className="space-y-3">{["name","company","contact_person","email","event_name"].map(k=><Field key={k} label={k.replace("_"," ")} value={form[k]} onChange={v=>setForm({...form,[k]:v})}/>)}<div className="grid grid-cols-2 gap-3"><Field label="Amount" type="number" value={form.amount} onChange={v=>setForm({...form,amount:v})}/><Field label="Tier" value={form.tier} onChange={v=>setForm({...form,tier:v})}/><Field label="Performance %" type="number" value={form.performance_score} onChange={v=>setForm({...form,performance_score:v})}/><Field label="ROI" type="number" value={form.roi} onChange={v=>setForm({...form,roi:v})}/></div><button className="btn-primary w-full">{editing?"Save changes":"Add sponsor"}</button></form></Card></div></div>;
 if(section==="incidents") return <div className="space-y-6"><header><h1 className="text-3xl font-bold">Incident Management</h1><p className="text-gray-500">Prioritized response queue with escalation workflow.</p></header><div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Stat label="Open" value={incidents.filter(x=>!["Resolved","Closed"].includes(x.status)).length}/><Stat label="Critical" value={incidents.filter(x=>x.priority==="Critical").length} accent="text-red-600"/><Stat label="Escalated" value={incidents.filter(x=>x.status==="Escalated").length} accent="text-orange-600"/><Stat label="Resolved" value={incidents.filter(x=>x.status==="Resolved").length} accent="text-emerald-600"/></div><div className="grid xl:grid-cols-3 gap-6"><Card className="xl:col-span-2 space-y-3">{incidents.map(i=><div key={i.id} className="p-4 rounded-xl border border-gray-100 hover:border-violet-200"><div className="flex justify-between gap-4"><div><div className="flex gap-2 items-center"><span className={`badge ${i.priority==="Critical"?"bg-red-100 text-red-700":i.priority==="High"?"bg-orange-100 text-orange-700":"bg-gray-100 text-gray-600"}`}>{i.priority}</span><b>{i.title}</b></div><p className="text-sm text-gray-500 mt-2">{i.description} • {i.location}</p><p className="text-xs text-gray-400 mt-2">{i.category} · Assigned to {i.assigned_to||"unassigned"} · Escalation L{i.escalation_level}</p></div><div className="flex flex-col gap-2"><select className="input py-1" value={i.status} onChange={e=>updateIncident(i.id,e.target.value)}><option>Open</option><option>Investigating</option><option>In Progress</option><option>Escalated</option><option>Resolved</option><option>Closed</option></select><button className="text-xs text-violet-600" onClick={()=>API.post(`/incidents/${i.id}/escalate`).then(load)}>Escalate ↗</button><button className="text-xs text-red-500" onClick={()=>remove(i.id,"incidents")}>Delete</button></div></div></div>)}</Card><Card><h2 className="font-bold mb-4">Create incident</h2><form onSubmit={saveIncident} className="space-y-3">{["title","description","location","event_name","reported_by","assigned_to"].map(k=><Field key={k} label={k.replace("_"," ")} value={incidentForm[k]} onChange={v=>setIncidentForm({...incidentForm,[k]:v})}/>)}<Field label="Category" value={incidentForm.category} onChange={v=>setIncidentForm({...incidentForm,category:v})}/><div className="grid grid-cols-2 gap-3"><Field label="Severity" value={incidentForm.severity} onChange={v=>setIncidentForm({...incidentForm,severity:v})}/><Field label="Priority" value={incidentForm.priority} onChange={v=>setIncidentForm({...incidentForm,priority:v})}/></div><button className="btn-primary w-full">Create incident</button></form></Card></div></div>;
 return <div className="space-y-6"><header><h1 className="text-3xl font-bold">{section==="sponsor-agent"?"Sponsorship Agent":"Incident Agent"}</h1><p className="text-gray-500">Ask the local rule-based agent about current operational data.</p></header><Card className="max-w-3xl"><textarea className="input min-h-28" placeholder={section==="sponsor-agent"?"Which sponsor has the highest ROI?":"Which incidents require immediate attention?"} value={question} onChange={e=>setQuestion(e.target.value)}/><button className="btn-primary mt-3" onClick={()=>ask(section==="sponsor-agent"?"sponsorship":"incident")}>Ask agent</button>{answer&&<div className="mt-5 p-4 rounded-xl bg-violet-50 text-violet-900"><b>Agent response</b><p className="mt-2">{answer}</p><small className="text-violet-500">Works offline without an API key.</small></div>}</Card></div>
}