import React,{useEffect,useState} from "react";
import {MdAdd,MdAutoAwesome,MdWarning} from "react-icons/md";
import {toast} from "react-toastify";
import API from "../api/axios.js";
import {PageHeader,LoadingState,EmptyState,ErrorState,Modal,CardActions,getList,value} from "../components/OperationsUI.jsx";

const blank={title:"",speaker_id:"",venue_id:"",start_time:"",end_time:"",expected_attendees:"",session_type:"General",required_equipment:"",required_expertise:"",status:"Draft"};
function Form({initial,speakers,venues,onSave,onClose,saving}){
  const[f,setF]=useState({...blank,...initial,speaker_id:initial?.speaker_id||"",venue_id:initial?.venue_id||""});
  const set=(key,val)=>setF(prev=>({...prev,[key]:val}));
  return <form onSubmit={e=>{e.preventDefault();onSave({...f,speaker_id:f.speaker_id?Number(f.speaker_id):null,venue_id:f.venue_id?Number(f.venue_id):null,expected_attendees:Number(f.expected_attendees||0)})}} className="grid sm:grid-cols-2 gap-4">
    <label className="label sm:col-span-2">Session title<input required className="input mt-1" value={f.title} onChange={e=>set("title",e.target.value)}/></label>
    <label className="label">Speaker<select className="input mt-1" value={f.speaker_id} onChange={e=>set("speaker_id",e.target.value)}><option value="">Unassigned</option>{speakers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
    <label className="label">Venue<select className="input mt-1" value={f.venue_id} onChange={e=>set("venue_id",e.target.value)}><option value="">Unassigned</option>{venues.map(v=><option key={v.id} value={v.id}>{v.name} · {v.capacity}</option>)}</select></label>
    <label className="label">Start time<input required type="datetime-local" className="input mt-1" value={f.start_time} onChange={e=>set("start_time",e.target.value)}/></label>
    <label className="label">End time<input required type="datetime-local" className="input mt-1" value={f.end_time} onChange={e=>set("end_time",e.target.value)}/></label>
    <label className="label">Expected attendees<input required type="number" min="0" className="input mt-1" value={f.expected_attendees} onChange={e=>set("expected_attendees",e.target.value)}/></label>
    <label className="label">Session type<input className="input mt-1" value={f.session_type} onChange={e=>set("session_type",e.target.value)}/></label>
    <label className="label">Required equipment<input className="input mt-1" placeholder="Projector, Wi-Fi" value={f.required_equipment} onChange={e=>set("required_equipment",e.target.value)}/></label>
    <label className="label">Required expertise<input className="input mt-1" placeholder="Artificial Intelligence" value={f.required_expertise} onChange={e=>set("required_expertise",e.target.value)}/></label>
    <label className="label">Status<select className="input mt-1" value={f.status} onChange={e=>set("status",e.target.value)}><option>Draft</option><option>Confirmed</option><option>Optimized</option><option>Cancelled</option></select></label>
    <div className="sm:col-span-2 flex justify-end gap-2"><button type="button" onClick={onClose} className="btn-secondary">Cancel</button><button disabled={saving} className="btn-primary">{saving?"Saving…":"Save session"}</button></div>
  </form>;
}
export default function Scheduling(){
  const[items,setItems]=useState([]),[speakers,setSpeakers]=useState([]),[venues,setVenues]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(false),[modal,setModal]=useState(null),[saving,setSaving]=useState(false),[conflicts,setConflicts]=useState([]),[auto,setAuto]=useState(null),[busy,setBusy]=useState(false);
  const load=()=>{setLoading(true);Promise.all([API.get("/sessions"),API.get("/schedule/conflicts"),API.get("/speakers"),API.get("/venues")]).then(([a,b,c,d])=>{setItems(getList(a.data,["sessions"]));setConflicts(getList(b.data,["conflicts"]));setSpeakers(getList(c.data,["speakers"]));setVenues(getList(d.data,["venues"]))}).catch(()=>setError(true)).finally(()=>setLoading(false))};
  useEffect(load,[]);
  const save=async f=>{setSaving(true);try{modal?.id?await API.put(`/sessions/${modal.id}`,f):await API.post("/sessions",f);toast.success("Session saved");setModal(null);load()}catch(e){toast.error(e.message)}finally{setSaving(false)}};
  const del=async id=>{if(!window.confirm("Delete this session?"))return;try{await API.delete(`/sessions/${id}`);toast.success("Session deleted");load()}catch(e){toast.error(e.message)}};
  const validate=async()=>{try{const r=await API.get("/schedule/conflicts");setConflicts(getList(r.data,["conflicts"]));toast.info("Schedule validated")}catch(e){toast.error(e.message)}};
  const schedule=async()=>{setBusy(true);try{const r=await API.post("/schedule/auto");setAuto(r.data);toast.success("AI schedule generated");load()}catch(e){toast.error(e.message)}finally{setBusy(false)}};
  return <div className="page-enter"><PageHeader eyebrow="Milestone 2 · Planning" title="Schedule studio" description="See the run of show, identify conflicts and let AI propose a cleaner day." action={<button onClick={()=>setModal({})} className="btn-primary inline-flex gap-2 items-center"><MdAdd/> Add session</button>}/>
    {loading?<LoadingState/>:error?<ErrorState onRetry={()=>{setError(false);load()}}/>:!items.length?<EmptyState title="Schedule is clear" text="Create a session to start building the timeline." action={<button onClick={()=>setModal({})} className="btn-primary">New session</button>}/>:<div className="space-y-3">{items.map(s=><div className="card flex flex-col sm:flex-row sm:items-center gap-4" key={s.id}><div className="w-28 text-center sm:border-r border-gray-100 pr-4"><p className="text-xs text-violet-500 font-bold">{value(s,["start_time"],"TBD").replace("T"," ")}</p><p className="text-xs text-gray-400">{value(s,["end_time"]).replace("T"," ")}</p></div><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold">{s.title}</h3><span className={`badge ${s.computed_status==="Conflict"?"bg-rose-100 text-rose-700":s.computed_status==="Optimized"?"bg-emerald-100 text-emerald-700":"bg-violet-100 text-violet-700"}`}>{s.computed_status||s.status}</span></div><p className="text-sm text-gray-500">{value(s.speaker,["name"],"Unassigned")} · {value(s.venue,["name"],"Unassigned")} · {s.expected_attendees} attendees</p>{s.conflicts?.length>0&&<p className="text-xs text-rose-600 mt-1">{s.conflicts.length} conflict{s.conflicts.length>1?"s":""} detected</p>}</div><CardActions onEdit={()=>setModal(s)} onDelete={()=>del(s.id)}/></div>)}</div>}
    <div className="grid lg:grid-cols-2 gap-4 mt-6"><div className="card"><div className="flex justify-between items-center"><h3 className="font-bold">Conflict monitor</h3><button onClick={validate} className="btn-secondary">Refresh conflicts</button></div>{conflicts.length?<div className="mt-4 space-y-2">{conflicts.map((c,i)=><div key={i} className="p-3 bg-rose-50 text-rose-700 rounded-xl text-sm flex gap-2"><MdWarning/>{c.session}: {c.message}</div>)}</div>:<p className="text-sm text-emerald-600 mt-4">No conflicts reported.</p>}</div><div className="card"><div className="flex justify-between items-center"><h3 className="font-bold flex gap-2 items-center"><MdAutoAwesome className="text-violet-600"/> AI auto schedule</h3><button onClick={schedule} disabled={busy} className="btn-primary">{busy?"Working…":"Run AI schedule"}</button></div>{auto&&<div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div className="bg-violet-50 rounded-xl p-3"><p className="text-xs text-gray-500">Sessions scheduled</p><strong>{auto.sessions_scheduled}</strong></div><div className="bg-emerald-50 rounded-xl p-3"><p className="text-xs text-gray-500">Conflicts resolved</p><strong>{auto.conflicts_resolved}</strong></div><p className="col-span-2 text-sm text-gray-600">{auto.message}</p></div>}</div></div>
    {modal&&<Modal title={modal.id?"Edit session":"New session"} onClose={()=>setModal(null)}><Form initial={modal} speakers={speakers} venues={venues} onSave={save} onClose={()=>setModal(null)} saving={saving}/></Modal>}
  </div>;
}